<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Post</name>
   <tag></tag>
   <elementGuidId>933176af-b9e1-460d-84be-c0754653806a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[33]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-md.submit-post.btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>42f77899-543c-4f68-be57-180b08b3d9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>345dc8f9-4c40-4706-a997-7a0fb3f7c39f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-md submit-post btn-primary</value>
      <webElementGuid>3859a8e0-acf7-43a8-91b6-0119d35cffbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
								Post
							</value>
      <webElementGuid>2c7f4886-ea15-4672-894a-462b30099715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-touchevents details js&quot;]/body[@class=&quot;path-public-feed user-logged-in has-glyphicons&quot;]/div[@class=&quot;dialog-off-canvas-main-canvas&quot;]/div[@class=&quot;main-container container js-quickedit-main-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;main row&quot;]/section[@class=&quot;col-sm-6 left-side-wrp&quot;]/div[@class=&quot;main-inner-wrp&quot;]/aside[@class=&quot;content-main&quot;]/div[@class=&quot;region region-content&quot;]/div[@class=&quot;views-element-container form-group&quot;]/div[@class=&quot;create-friends-post popup pip&quot;]/div[@class=&quot;create-post&quot;]/div[@class=&quot;row row-no-gutters post-form&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;add-feed-form&quot;]/div[@class=&quot;submit&quot;]/button[@class=&quot;btn btn-md submit-post btn-primary&quot;]</value>
      <webElementGuid>98d84d30-93b5-4f88-bcc9-bc38bd533c51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[33]</value>
      <webElementGuid>fc876575-fa8c-42c5-83e9-2a0a178e2686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::button[1]</value>
      <webElementGuid>303e6132-ec27-4ef4-8c9a-34f4c7086a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::button[1]</value>
      <webElementGuid>1b411ed8-ca24-483c-b7b5-fac6c6680498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/button</value>
      <webElementGuid>9dfe9dc5-66c3-4036-94ba-39cdccaeb7f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
								Post
							' or . = '
								Post
							')]</value>
      <webElementGuid>d111fc26-d95e-41c1-8b1d-fc181b4e1f14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
