<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rajapriya Muthuvel_feed-title</name>
   <tag></tag>
   <elementGuidId>c35e57be-2d87-478b-a5a2-76bc934fdbf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='feed-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;feed-title&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a00ee25-9a66-4c85-b061-05cb114f9e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>70f2e7e6-d4b3-4afa-8c34-f44c10981aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control feed-title</value>
      <webElementGuid>5965566b-2879-47e9-869a-02a2af67e08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write post title</value>
      <webElementGuid>0d0894bc-cf1d-48aa-8981-e09ad2e50aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>feed-title</value>
      <webElementGuid>d31a3a15-5f1c-4924-b3b5-e732e018760c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-touchevents details js&quot;]/body[@class=&quot;path-public-feed user-logged-in has-glyphicons&quot;]/div[@class=&quot;dialog-off-canvas-main-canvas&quot;]/div[@class=&quot;main-container container js-quickedit-main-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;main row&quot;]/section[@class=&quot;col-sm-6 left-side-wrp&quot;]/div[@class=&quot;main-inner-wrp&quot;]/aside[@class=&quot;content-main&quot;]/div[@class=&quot;region region-content&quot;]/div[@class=&quot;views-element-container form-group&quot;]/div[@class=&quot;create-friends-post popup pip&quot;]/div[@class=&quot;create-post&quot;]/div[@class=&quot;row row-no-gutters post-form&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;add-feed-form&quot;]/div[@class=&quot;add-feed-form-inputs-elements&quot;]/form[1]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control feed-title&quot;]</value>
      <webElementGuid>2085ce52-3a09-496e-bd09-f74bbf76ce29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='feed-title']</value>
      <webElementGuid>4254b6b6-a423-494e-94e0-33ee84b16a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/form/div/input</value>
      <webElementGuid>b135de38-a508-44a2-8506-efca1881a7bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Write post title' and @name = 'feed-title']</value>
      <webElementGuid>9378699f-660f-41d6-bd57-a684fdc7c833</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
