<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PublicFriends</name>
   <tag></tag>
   <elementGuidId>1300d320-d0b4-4746-befb-7f4aecf93002</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='feed-permission']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;feed-permission&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>09cdfa80-b599-4851-8563-624df3f2a6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feed-permission</value>
      <webElementGuid>2c3f914d-7ee6-49c5-8556-de0f3c1926a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>feed-permission</value>
      <webElementGuid>42215d1d-7daa-4b47-a031-16370750a197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
									Public
									Friends
						</value>
      <webElementGuid>fa430716-9f57-4eef-9af7-b42390374cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-touchevents details js&quot;]/body[@class=&quot;path-public-feed user-logged-in has-glyphicons&quot;]/div[@class=&quot;dialog-off-canvas-main-canvas&quot;]/div[@class=&quot;main-container container js-quickedit-main-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;main row&quot;]/section[@class=&quot;col-sm-6 left-side-wrp&quot;]/div[@class=&quot;main-inner-wrp&quot;]/aside[@class=&quot;content-main&quot;]/div[@class=&quot;region region-content&quot;]/div[@class=&quot;views-element-container form-group&quot;]/div[@class=&quot;create-friends-post popup pip&quot;]/div[@class=&quot;create-post&quot;]/div[@class=&quot;row row-no-gutters&quot;]/div[@class=&quot;col-xs-9 create-post-user-detail&quot;]/div[@class=&quot;create-post-permission&quot;]/select[@class=&quot;feed-permission&quot;]</value>
      <webElementGuid>e1c6aec4-af64-4313-bccc-5f7a0be8b850</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='feed-permission']</value>
      <webElementGuid>ca5add14-6fa9-49b5-ae46-7687b5d81e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rajapriya Muthuvel'])[1]/following::select[1]</value>
      <webElementGuid>9776cb5b-503b-467a-8c92-7ee015437d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Post'])[2]/following::select[1]</value>
      <webElementGuid>5df58062-fec2-4007-9fc9-c92d67ef8c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add To Post'])[1]/preceding::select[1]</value>
      <webElementGuid>994032e6-6dac-401b-8bb0-f851245918f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>2ce9ccc2-a6ac-41de-94f7-283b71ffa168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'feed-permission' and (text() = '
									Public
									Friends
						' or . = '
									Public
									Friends
						')]</value>
      <webElementGuid>a45f2dfc-d7f5-43ac-920f-1db8e4b40f71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
