<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_X_field_friends_images_caption_0</name>
   <tag></tag>
   <elementGuidId>6d2a93c1-c7d4-42bc-9680-a467f971e24a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='field_friends_images_caption_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#field_friends_images_caption_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e4e64d56-391b-457a-a1d1-f178ecfd256c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field_friends_images_caption_0</value>
      <webElementGuid>933abb57-c16d-460c-9b3c-d7e24679f534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b57fa73b-4c13-41ad-a202-385b58ea4f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Caption</value>
      <webElementGuid>e534398a-7440-4e9d-937b-aea43bd8e1af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control friends-image-caption</value>
      <webElementGuid>f475684e-c88d-4354-979b-ce3280f41885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field_friends_images_caption_0&quot;)</value>
      <webElementGuid>5aa55a22-3d45-423f-88e5-c450a13e1b77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='field_friends_images_caption_0']</value>
      <webElementGuid>688e18bc-5184-40a8-996b-bef3651d8c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frn-post-image-div-0']/textarea</value>
      <webElementGuid>fdee43d4-89b4-4808-b3f7-0d27f03d7361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/textarea</value>
      <webElementGuid>b9c4bd18-4dd6-4e90-b834-c8febbe1693a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'field_friends_images_caption_0' and @placeholder = 'Caption']</value>
      <webElementGuid>6ad7975e-37a4-41d3-839f-c9254bd96eae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
