<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Rajapriya Muthuvel_feed-body</name>
   <tag></tag>
   <elementGuidId>b76e1a96-d2e5-481c-b1f4-20b1548aea5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='feed-body']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;feed-body&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>eaec68cd-9c31-43d5-80f3-58e730e5583b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>feed-body</value>
      <webElementGuid>2d3ba21d-b69a-4b4e-94a0-309c021ad586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control feed-body</value>
      <webElementGuid>55103e7e-4fda-4b4e-a1ed-22799c19509a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>ac4aaef3-1456-4dbb-99f3-a13adb8afbed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7175497f-246a-4366-86f0-005f88014521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write post details</value>
      <webElementGuid>57ec2cd5-506f-4076-88af-1ac06d2988e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-touchevents details js&quot;]/body[@class=&quot;path-public-feed user-logged-in has-glyphicons&quot;]/div[@class=&quot;dialog-off-canvas-main-canvas&quot;]/div[@class=&quot;main-container container js-quickedit-main-content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;main row&quot;]/section[@class=&quot;col-sm-6 left-side-wrp&quot;]/div[@class=&quot;main-inner-wrp&quot;]/aside[@class=&quot;content-main&quot;]/div[@class=&quot;region region-content&quot;]/div[@class=&quot;views-element-container form-group&quot;]/div[@class=&quot;create-friends-post popup pip&quot;]/div[@class=&quot;create-post&quot;]/div[@class=&quot;row row-no-gutters post-form&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;add-feed-form&quot;]/div[@class=&quot;add-feed-form-inputs-elements&quot;]/form[1]/div[@class=&quot;form-group&quot;]/textarea[@class=&quot;form-control feed-body&quot;]</value>
      <webElementGuid>092140df-7053-4e7c-8f16-b9b451da0c4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='feed-body']</value>
      <webElementGuid>797ea348-84fd-46be-82d4-aaf0f5c89aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/textarea</value>
      <webElementGuid>07b2801b-11e6-4920-8e2f-d1d88bc2dcfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'feed-body' and @placeholder = 'Write post details']</value>
      <webElementGuid>db1eafe6-c14e-40ac-9413-dd3e3246adcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
